### ISSUE TITLE
Different image size with same intrinsics between your training data and data from MVSNet_pytorch.

### ISSUE THREAD

**Issue by zhuixunforever** [JiayuYANG/CVP-MVSNet#10]
@JiayuYANG  Hi, thank you for your great work. 
I notice the intrinsics of your [training data](https://github.com/JiayuYANG/CVP-MVSNet#6-train-your-own-model) is the same with the data from [MVSNet_pytorch](https://github.com/xy-guo/MVSNet_pytorch#training), but the image size of them is different, your training image is 128x160, MVSNet_pytorch is 512x640.
e.g.
The camera parameters of your training data in _dtu-train-128/Cameras/00000000_cam.txt_  is:
![image](https://user-images.githubusercontent.com/9960172/91954582-8f828780-ed34-11ea-825c-74a383f24708.png)

But the camera parameters of MVSNet_pytorch 's data in _mvs_training/dtu/Cameras/train/00000000_cam.txt_ is:
![image](https://user-images.githubusercontent.com/9960172/91955339-98c02400-ed35-11ea-8c2b-4e1b35c43fc2.png)

Does that have no effect on training results, and the final inference?
I am confused because I think the intrinsics should be scaled down.

By the way, the different scale fx/fy/cx/cy between test data and train data in MVSNet_pytorch makes me confused too.
          test      |     train          |   scale
H       1200    |      512           |    2.22
W      1600    |      640           |    2.5
fx    2892.33  |   361.54125   |    8.0
fy    2883.18  |  360.3975      |    8.0
cx   823.205  |  82.900625     |   9.93
cy   619.071  |  66.383875     |   9.33

**Comment by JiayuYANG** [comment]
Hi @zhuixunforever 

MVSNet take high resolution image as input and extract feature map of size 160x128, which is 1/4 of the input image size.
Our network directly take 160x128 image as input and extract feature maps of the same size.
So both networks do warping on the 160x128 feature map, thus the same intrinsics.

About the second question, 
the training data is down sampled **and center cropped** from the original 1600x1200 image.
e.g.:
Image from dataset: 1600x1200
-> downsample to 800x600
-> center crop to 640x512
-> use for training. 

Thus the scale is different. You need to count in the center cropping.
You can check MVSNet paper for more details.

Cheers,
Jiayu.

**Comment by zhuixunforever** [comment]
Thank you for your reply, I understand it.
