### ISSUE TITLE
depth_refine in pretrained model

### ISSUE THREAD

**Issue by jytime** [JiayuYANG/CVP-MVSNet#11]
Hi,

I found it will report unexpected keys when loading the provided ckpt. Is this depth_refine module abandoned or renamed in the final version?  I was wondering if we need to change some settings here.

![image](https://user-images.githubusercontent.com/37647961/92331511-afee7100-f0a9-11ea-957d-5ed7a05c3354.png)

**Comment by JiayuYANG** [comment]
Hi @jytime ,

Yes, that module is deprecated.
To reproduce exactly same results as we report in paper, the pretrained checkpoint I provided is the one we used to get the results.
That module was in our network at that time, but is deprecated now.

I think I've set `strict=False` in [this line](https://github.com/JiayuYANG/CVP-MVSNet/blob/master/CVP_MVSNet/eval.py#L73) to ignore that module.

You can safely ignore that module, and if you would like to use that checkpoint, you can also use `strict=False`.

Cheers,
Jiayu.
