### ISSUE TITLE
Found 0.00 million points

### ISSUE THREAD

**Issue by alanlyawen** [JiayuYANG/CVP-MVSNet#12]
Hi,thanks for your work, and when I use my own datasets train a model,but when fusion with depths,I cant get results
of point clounds without any error information, so I guess maybe the para settings of fusion code can you give any information about it thanks very much! And my own datasets is with size of 960x540 and 30 cameras.

**Comment by JiayuYANG** [comment]
Hi @alanlyawen 

If you are working on your own dataset, there are many things that may cause this problem.

Few things to check:
1. Does the estimated depth map looks good?
2. Is your geometric threshold too small? ([this line](https://github.com/JiayuYANG/CVP-MVSNet/blob/master/CVP_MVSNet/fusion/fusion.sh#L16))
3. Is your fusibile compiled correctly?
4. Is the image and camera parameters correct in fusibile?
5. Any scaling required for camera parameters?

Cheers,
Jiayu.

**Comment by alanlyawen** [comment]
> Hi @alanlyawen
> 
> If you are working on your own dataset, there are many things that may cause this problem.
> 
> Few things to check:
> 
> 1. Does the estimated depth map looks good?
> 2. Is your geometric threshold too small? ([this line](https://github.com/JiayuYANG/CVP-MVSNet/blob/master/CVP_MVSNet/fusion/fusion.sh#L16))
> 3. Is your fusibile compiled correctly?
> 4. Is the image and camera parameters correct in fusibile?
> 5. Any scaling required for camera parameters?
> 
> Cheers,
> Jiayu.

Thank you very much！
