### ISSUE TITLE
How to compute the f-score of DTU point cloud ?

### ISSUE THREAD

**Issue by XYZ-qiyh** [JiayuYANG/CVP-MVSNet#16]
Hi, @JiayuYANG 
How to compute the `f-score` for DTU dataset, as described in Table 2 in your paper?

**Comment by JiayuYANG** [comment]
Hi, @Todd-Qi 

The matlab evaluation code provided by DTU dataset calculate the accuracy and completeness score.
You can modify the code to also calculate precision, recall and f-score based on their [definition](https://en.wikipedia.org/wiki/F-score).

Cheers,
Jiayu

**Comment by XYZ-qiyh** [comment]
Got it. Thank you!
