### ISSUE TITLE
Hi,can you share some detail 

### ISSUE THREAD

**Issue by alanlyawen** [JiayuYANG/CVP-MVSNet#18]
When test in tank&temples dataset,the fusion parameters should be set as? And depth intervals  follow MVSNet?
Tank you very much!!!

**Comment by JiayuYANG** [comment]
Hi @alanlyawen 

If I remember correctly, we used following parameters on Tanks and Temples dataset.
```
prob_threshold=0.94
disp_threshold=0.20
num_consistent=3
```

We did not do many validation of these parameters on Tanks and Temples dataset. There might be better settings.
You can start with these numbers.

About depth intervals, we use the same way to calculate refine interval as introduced in our paper.
And the initial depth planes I used is 192 if I remember correctly.

Cheers,
Jiayu

**Comment by alanlyawen** [comment]
Tanks for your answer!
