### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by jackyangs** [JiayuYANG/CVP-MVSNet#19]
Hello, how do you get the accuracy rate?
I've downloaded the matlab code now, but I don't know how to use it.

**Comment by JiayuYANG** [comment]
Hi @jackyangs 

The script to run the evaluation is BaseEvalMain_web.m
After setting correct path to the DTU dataset and the ply files you generated, you can run this script to start the evaluation.

Regards.
Jiayu.

**Comment by lhx0416** [comment]
> 

hello,I have downloaded the matlab code,however in "BaseEvalMain_web.m", there are disp("acc") and disp("comp"), but i don't see the calculated equation of them. can you help me? thanks a lot.
![image](https://user-images.githubusercontent.com/71110348/194686897-5887dc5d-a7ad-47ae-a9ce-20f60aedce39.png)
