### ISSUE TITLE
coda=2(cudaErrorMemoryallocation)  when run fusible in 'Tanks and Temples'

### ISSUE THREAD

**Issue by zhuixunforever** [JiayuYANG/CVP-MVSNet#20]
When I fuse the depth map of Tanks and Temples by Yao Yao's [fusibile](https://github.com/JiayuYANG/CVP-MVSNet#5-generate-point-clouds-and-reproduce-dtu-results), I meet this error. 
Specifically, I meet this error with the scene Francis(302 images), Lighthouse(309 images), M60(313 images), Panther(314 images), Playground(307 images), Train(301 images). The scene Family(152 images) and Horse(151 images) can run successfully. The image size is 1056x1920 or 1056x2048. 
This seems to be a problem of out of memory.  My GPU is RTX2080Ti.  Did you meet this problem?

**Comment by JiayuYANG** [comment]
Hi @zhuixunforever 

I have not met this problem before.
I doubt if it's the problem of gpu memory, as normally fusibile don't use too much memory on my machine.
But to check this part, you might want to try to reduce the number of images input to fusibile to reduce memory consumption and see if it can run with no errors.

Regards.
Jiayu.

**Comment by Sun-Xinnnnn** [comment]
> 

Thank you very much for the author's paper and code, but I found a dimension error after modifying the data set configuration code and path, so I would like to ask if you can send the test code of T&T to my email address? Thank you very much and look forward to your reply: )

**Comment by Fourpk** [comment]
Can you send me the test code of T&T to my email address? 3213558082@qq.com
Thank you!
