### ISSUE TITLE
Google Colab notebook?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [JiayuYANG/CVP-MVSNet#21]
Thanks for making this code avaiable!  would you consider making a google colab notebook so people who are not as technically proficient like myself can try it out?  thanks in advance!

**Comment by JiayuYANG** [comment]
Hi @noobtoob4lyfe 

I'm not familiar with Google Colab at all so I might not be able to provide much help on that.
Besides, I think the setup of multi-view stereo problem might not be suitable for Colab?
Also, visualization of dense 3D point cloud might be too heavy for Colab.
I think it might be better to run it on a local machine with sufficient disk space, CPU memory and GPU memory.

Cheers,
Jiayu.
