### ISSUE TITLE
Normal Map

### ISSUE THREAD

**Issue by caoPhoenix** [JiayuYANG/CVP-MVSNet#25]
How to generate normal map and render it like your paper presented?
![image](https://user-images.githubusercontent.com/31002014/116215179-0401af00-a77a-11eb-9fc6-1aab9c550bf5.png)

Could the normal map be generated directly from the point cloud( i.e. the `.ply` file) ?

**Comment by JiayuYANG** [comment]
Hi @caoPhoenix 

My pipeline to generate this figure:
1. Open .ply with [CloudCompare](https://www.danielgm.net/cc/)
2. Click the point cloud object on the DB Tree (left panel) (The entry with a small cloud icon), make sure it is highlighted.
3. Click Edit -> Normal -> Compute
4. Click Edit -> Normal -> Convert to -> HSV colors
5. Adjust viewpoint
6. Click Display -> Render to file

You might want to adjust the parameters in each dialogue.

Cheers,
Jiayu.

**Comment by caoPhoenix** [comment]
Thanks for your prompt replying!
It would be very helpful!
