### ISSUE TITLE
Test on custom dataset

### ISSUE THREAD

**Issue by CanCanZeng** [JiayuYANG/CVP-MVSNet#4]
Hi @JiayuYANG , thank you for sharing this great project, I tried the dtu dataset, the result is very impressive.
But I'm troubling in testing on other dataset such as ETH3D, I changed the dataset loader code, but since the image size is different, there is an error says "shape '[1, 1, 8, 7605]' is invalid for input of size 59392"
Can you provide a script to show how to test the network on other dataset? Or if you can give me some advice

**Comment by JiayuYANG** [comment]
Hi @CanCanZeng , 

Currently we don't have a dataloader for ETH3D ready for release.

Could you provide more information on the error?
e.g. which line of code does the error reported? What's the tensor that has invalid shape?
It would be great if you could provide a minimal example to reproduce your error.

Cheers,
Jiayu
