### ISSUE TITLE
fusion.sh

### ISSUE THREAD

**Issue by Liyuanzhen1992** [JiayuYANG/CVP-MVSNet#5]
when I run fusion.sh, have a bug:
data = np.fromstring(data_string, data_type)
ValueError: string size must be a multiple of element size

your code is"

   scale = float((file.readline()).decode('UTF-8').rstrip())
    if scale < 0: # little-endian
        data_type = '<f'
    else:
        data_type = '>f' # big-endian
    data_string = file.read()
    #data = np.fromstring(data_string)
    data = np.fromstring(data_string, "data_type")

**Comment by JiayuYANG** [comment]
Hi @Liyuanzhen1992 ,

That part of code is for reading the .pfm file, which contains a depth map or a probability map.
I think it is something related to your input. Is your .pfm file generated correctly?

Cheers,
Jiayu
