### ISSUE TITLE
Evaluation on Tanks and Temples dataset

### ISSUE THREAD

**Issue by ToughStoneX** [JiayuYANG/CVP-MVSNet#6]
Hi @JiayuYANG , thanks for sharing the codes of your paper. The codes work fine on DTU dataset. Currently, I want to apply the codes to Tanks and Temples dataset(provided by MVSNet), which is also mentioned in your paper. Although I have already modified the dataloader by adjusting the camera intrinsics according to the image resolution, I am still not able to run the code correctly. I can not find any instructions and replys about the Tanks and Temple dataset in other repos in github. Could you provide the evaluation code or the dataloader of Tanks and Temples dataset? Thanks a lot!!!

**Comment by Fourpk** [comment]
May I ask if you have solved the problem now?Can you send me the test code of T&T to my email address? [3213558082@qq.com](mailto:3213558082@qq.com)
Thank you very much!
